{% set name = "clusterscope" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/clusterscope-{{ version }}.tar.gz
  sha256: c6f66ded4c1329ee6f42c2b91bd05217f22a7d09757c41d040a3dbd7e7ddddcb

build:
  entry_points:
    - cscope = clusterscope.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - clusterscope
  commands:
    - pip check
    - cscope --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facebookresearch/clusterscope
  summary: clusterscope is a python library to extract core information from HPC Clusters
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
