schema_version: 1

context:
  name: clusterscope
  version: "0.0.15"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/clusterscope-${{ version }}.tar.gz
  sha256: b68eda58ccd6d1ccf0d63e9f6d1646e0d0b788a6dbf6c504a412dab15b411de7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cscope = clusterscope.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=75
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - clusterscope
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - cscope --help

about:
  summary: clusterscope is a python library to extract core information from HPC Clusters
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/facebookresearch/clusterscope

extra:
  recipe-maintainers:
    - jan-janssen
