schema_version: 1

context:
  name: clusterscope
  version: "0.0.26"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/clusterscope-${{ version }}.tar.gz
  sha256: f689a1a40a9df37d8c44a5b9dee74ea391c789568109ad06acdba21752321a03

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cscope = clusterscope.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=75
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=${{ python_min }}
    - click >=8.0.0,!=8.3.0
    - click-option-group
tests:
  - python:
      imports:
        - clusterscope
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - cscope --help

about:
  summary: clusterscope is a python library to extract core information from HPC Clusters
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/facebookresearch/clusterscope

extra:
  recipe-maintainers:
    - jan-janssen
